# Generated by Django 5.1 on 2024-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook_text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
