# Generated by Django 5.1.1 on 2024-12-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_options_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
